### ISSUE TITLE
Propagate visual notification in task bar and tabs

### ISSUE THREAD

**Issue by nmussy** [sentialx/multrin#45]
It'd be nice for the application to use [win.flashFrame](https://github.com/electron/electron/blob/master/docs/api/browser-window.md#winflashframeflag) or [dock.bounce](https://github.com/electron/electron/blob/master/docs/api/dock.md#dockbouncetype-macos) when one of the windows warrants attention, and have its tab have an indicator if it's not currently focused.

One use case for this would be to create a multrin of different messaging applications.

**Comment by sentialx** [comment]
In Windows I would need to inject a DLL to associated process with attached window to Multrin to fetch notifications, so I think it's not a good idea (but maybe there is a different way to do it, which I don't know about). In macOS unfortunately, there is really a few doable things, since the Accessibility API is really limited and even not well-documented. Anyway, thanks for your suggestion, maybe someone could help me with that in the future.

**Comment by nmussy** [comment]
Looking into the Windows side of things, it seems you could catch the flashing with the [Shell hook API](https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-registershellhookwindow). But that would require adding some C-like into the project, yes.

**Comment by sentialx** [comment]
It is not a problem to inclue C/C++ into it, since node-window-manager is written mainly in C++ as a native node addon, but I'm afraid the Shell hook would require DLL injecting which I would rather like to avoid.

**Comment by sentialx** [comment]
Closing as wontfix
