### ISSUE TITLE
Minimize problems?

### ISSUE THREAD

**Issue by juanferrer** [sentialx/multrin#49]
When minimizing Multrin, the focused tab remains visible. If the tab (now a window) is selected and moved, it detaches from Multrin.

**Comment by sentialx** [comment]
On what OS are you running Multrin?

**Comment by juanferrer** [comment]
Windows 10, 64-bit. Build 1803.

**Comment by sentialx** [comment]
Fixed in ec3de30127bc626e15b1add2da28ddcf032b5561

**Comment by modulexcite** [comment]
Thank you for a great app @sentialx. 
I ran into the same problem as @juanferrer and glad to see that you have already addressed it, any updates on when we can expect a new release. On a similar note, is it possible to add an option to **minimize to tray** on Windows instead of closing the app when pressing **X**? Please let me know if you prefer I open a new issue for this, thanks again.

**Comment by sentialx** [comment]
It would be more convenient to create a new issue for this.
