### ISSUE TITLE
Not stacking instances of multrin

### ISSUE THREAD

**Issue by DaKie206** [sentialx/multrin#59]

**Comment by sentialx** [comment]
What do you mean?

**Comment by DaKie206** [comment]
When you open multiple instances of multrin in Windows they stack on one icon and you have to select one instance when you hover over the multrin icon. I would like if they would be beside each other

**Comment by sentialx** [comment]
@DaKie206 Could you send a screenshot?

**Comment by DaKie206** [comment]
![image](https://user-images.githubusercontent.com/50425705/62461882-4d2ff500-b786-11e9-8638-1922b92711f6.png)

**Comment by sentialx** [comment]
Well, that's not a Multrin issue. You can try changing the Windows 10 taskbar behavior.

**Comment by DaKie206** [comment]
I just want it for multrin not for my other windows

**Comment by DrPepperBianco** [comment]
Change Windows 10 taskbar behavior is not what this issue meant! - I also see the need for this.

Here is a useful link for background information:
https://msdn.microsoft.com/en-us/magazine/dd942846.aspx

In a nutshell: Windows stacks Windows that correspond. But an application can of course have multiple windows that should not stack. Or have two seperate groups etc.

Because Multrin stacks multiple Windows for us, the Multrin Windows themselves should not be grouped.

Maybe this can be added sometimes.

BTW I tried having multiple exe files (copy and renaming Multrin.exe) but that didn't work. So the Application itself sends some Information to Windows so that the windows be stacked.

**Comment by sentialx** [comment]
@DrPepperBianco Thanks for more detailed info about this issue, I will consider fixing this.

**Comment by DrPepperBianco** [comment]
As a workaround: The software "7+ Taskbar Tweaker" has the feature to block grouping of Taskbar buttons for specific apps, while leaving grouping intact for all others.
https://rammichael.com/7-taskbar-tweaker

**Comment by sentialx** [comment]
Closing it as wontfix
